{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPRLiKTmCe4KfjQ7ZX07pyW",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Ibrahim-Abduljabar/monkey-Ai/blob/main/test_py_and_ML2.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "! pip install streamlit\n",
        "! pip install pyngrok"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "VjPXBqJ3sLXe",
        "outputId": "5812c549-b458-4208-af2f-b2b2cc72d515"
      },
      "execution_count": 7,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: streamlit in /usr/local/lib/python3.12/dist-packages (1.57.0)\n",
            "Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)\n",
            "Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)\n",
            "Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)\n",
            "Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.3.3)\n",
            "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.47)\n",
            "Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)\n",
            "Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.1)\n",
            "Requirement already satisfied: pandas<4,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)\n",
            "Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)\n",
            "Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.9.2)\n",
            "Requirement already satisfied: protobuf<8,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)\n",
            "Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)\n",
            "Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)\n",
            "Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)\n",
            "Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)\n",
            "Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)\n",
            "Requirement already satisfied: starlette>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.52.1)\n",
            "Requirement already satisfied: uvicorn>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.46.0)\n",
            "Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.7.1)\n",
            "Requirement already satisfied: anyio>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.13.0)\n",
            "Requirement already satisfied: python-multipart>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.0.26)\n",
            "Requirement already satisfied: websockets>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (15.0.1)\n",
            "Requirement already satisfied: itsdangerous>=2.1.2 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.0)\n",
            "Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)\n",
            "Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)\n",
            "Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.20.0)\n",
            "Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio>=4.0.0->streamlit) (3.13)\n",
            "Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)\n",
            "Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2025.2)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4,>=1.4.0->streamlit) (2026.1)\n",
            "Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.7)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.4.22)\n",
            "Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)\n",
            "Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)\n",
            "Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)\n",
            "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)\n",
            "Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)\n",
            "Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)\n",
            "Collecting pyngrok\n",
            "  Downloading pyngrok-8.1.2-py3-none-any.whl.metadata (8.6 kB)\n",
            "Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.3)\n",
            "Downloading pyngrok-8.1.2-py3-none-any.whl (25 kB)\n",
            "Installing collected packages: pyngrok\n",
            "Successfully installed pyngrok-8.1.2\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 22,
      "metadata": {
        "id": "kZaxAGxMsJc0"
      },
      "outputs": [],
      "source": [
        "import streamlit as st\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "import pyngrok as norok\n",
        "from sklearn.linear_model import  LinearRegression\n",
        "from sklearn.preprocessing import LabelEncoder\n",
        "from sklearn.model_selection import train_test_split\n",
        "from sklearn.metrics import mean_squared_error\n",
        "from sklearn.ensemble import RandomForestClassifier\n",
        "from sklearn.ensemble import RandomForestRegressor\n",
        "from sklearn.decomposition import PCA\n",
        "import os"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "monkey = RandomForestRegressor()"
      ],
      "metadata": {
        "id": "PR3qXYZlsPAj"
      },
      "execution_count": 23,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "x = pd.DataFrame({\n",
        "     \"Hours\":[1,2,3,4,5,6,7,8,9,10,11,12,13,14],\n",
        "     \"drink\":[\"coffee\",\"juice\",\"tea\",\"coffee\",\"juice\",\"tea\",\"coffee\",\"coffee\",\"juice\",\"tea\",\"coffee\",\"juice\",\"tea\",\"coffee\"]\n",
        "})\n",
        "\n",
        "le = LabelEncoder()\n",
        "x['drink'] = le.fit_transform(x['drink'])\n",
        "y = np.array([44,60,65,70,80,91,94,100,122,140,170,180,191,194])\n",
        "pca = PCA(n_components=1)\n",
        "x = pca.fit_transform(x)\n",
        "x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.20,random_state=42)\n",
        "sns.regplot(x=x, y=y )\n",
        "monkey.fit(x_train,y_train)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 493
        },
        "id": "9SJX_GEHsPUe",
        "outputId": "58fd57d2-2b28-4cd6-c8d8-9b80a6537abb"
      },
      "execution_count": 24,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "RandomForestRegressor()"
            ],
            "text/html": [
              "<style>#sk-container-id-5 {\n",
              "  /* Definition of color scheme common for light and dark mode */\n",
              "  --sklearn-color-text: #000;\n",
              "  --sklearn-color-text-muted: #666;\n",
              "  --sklearn-color-line: gray;\n",
              "  /* Definition of color scheme for unfitted estimators */\n",
              "  --sklearn-color-unfitted-level-0: #fff5e6;\n",
              "  --sklearn-color-unfitted-level-1: #f6e4d2;\n",
              "  --sklearn-color-unfitted-level-2: #ffe0b3;\n",
              "  --sklearn-color-unfitted-level-3: chocolate;\n",
              "  /* Definition of color scheme for fitted estimators */\n",
              "  --sklearn-color-fitted-level-0: #f0f8ff;\n",
              "  --sklearn-color-fitted-level-1: #d4ebff;\n",
              "  --sklearn-color-fitted-level-2: #b3dbfd;\n",
              "  --sklearn-color-fitted-level-3: cornflowerblue;\n",
              "\n",
              "  /* Specific color for light theme */\n",
              "  --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n",
              "  --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, white)));\n",
              "  --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, black)));\n",
              "  --sklearn-color-icon: #696969;\n",
              "\n",
              "  @media (prefers-color-scheme: dark) {\n",
              "    /* Redefinition of color scheme for dark theme */\n",
              "    --sklearn-color-text-on-default-background: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n",
              "    --sklearn-color-background: var(--sg-background-color, var(--theme-background, var(--jp-layout-color0, #111)));\n",
              "    --sklearn-color-border-box: var(--sg-text-color, var(--theme-code-foreground, var(--jp-content-font-color1, white)));\n",
              "    --sklearn-color-icon: #878787;\n",
              "  }\n",
              "}\n",
              "\n",
              "#sk-container-id-5 {\n",
              "  color: var(--sklearn-color-text);\n",
              "}\n",
              "\n",
              "#sk-container-id-5 pre {\n",
              "  padding: 0;\n",
              "}\n",
              "\n",
              "#sk-container-id-5 input.sk-hidden--visually {\n",
              "  border: 0;\n",
              "  clip: rect(1px 1px 1px 1px);\n",
              "  clip: rect(1px, 1px, 1px, 1px);\n",
              "  height: 1px;\n",
              "  margin: -1px;\n",
              "  overflow: hidden;\n",
              "  padding: 0;\n",
              "  position: absolute;\n",
              "  width: 1px;\n",
              "}\n",
              "\n",
              "#sk-container-id-5 div.sk-dashed-wrapped {\n",
              "  border: 1px dashed var(--sklearn-color-line);\n",
              "  margin: 0 0.4em 0.5em 0.4em;\n",
              "  box-sizing: border-box;\n",
              "  padding-bottom: 0.4em;\n",
              "  background-color: var(--sklearn-color-background);\n",
              "}\n",
              "\n",
              "#sk-container-id-5 div.sk-container {\n",
              "  /* jupyter's `normalize.less` sets `[hidden] { display: none; }`\n",
              "     but bootstrap.min.css set `[hidden] { display: none !important; }`\n",
              "     so we also need the `!important` here to be able to override the\n",
              "     default hidden behavior on the sphinx rendered scikit-learn.org.\n",
              "     See: https://github.com/scikit-learn/scikit-learn/issues/21755 */\n",
              "  display: inline-block !important;\n",
              "  position: relative;\n",
              "}\n",
              "\n",
              "#sk-container-id-5 div.sk-text-repr-fallback {\n",
              "  display: none;\n",
              "}\n",
              "\n",
              "div.sk-parallel-item,\n",
              "div.sk-serial,\n",
              "div.sk-item {\n",
              "  /* draw centered vertical line to link estimators */\n",
              "  background-image: linear-gradient(var(--sklearn-color-text-on-default-background), var(--sklearn-color-text-on-default-background));\n",
              "  background-size: 2px 100%;\n",
              "  background-repeat: no-repeat;\n",
              "  background-position: center center;\n",
              "}\n",
              "\n",
              "/* Parallel-specific style estimator block */\n",
              "\n",
              "#sk-container-id-5 div.sk-parallel-item::after {\n",
              "  content: \"\";\n",
              "  width: 100%;\n",
              "  border-bottom: 2px solid var(--sklearn-color-text-on-default-background);\n",
              "  flex-grow: 1;\n",
              "}\n",
              "\n",
              "#sk-container-id-5 div.sk-parallel {\n",
              "  display: flex;\n",
              "  align-items: stretch;\n",
              "  justify-content: center;\n",
              "  background-color: var(--sklearn-color-background);\n",
              "  position: relative;\n",
              "}\n",
              "\n",
              "#sk-container-id-5 div.sk-parallel-item {\n",
              "  display: flex;\n",
              "  flex-direction: column;\n",
              "}\n",
              "\n",
              "#sk-container-id-5 div.sk-parallel-item:first-child::after {\n",
              "  align-self: flex-end;\n",
              "  width: 50%;\n",
              "}\n",
              "\n",
              "#sk-container-id-5 div.sk-parallel-item:last-child::after {\n",
              "  align-self: flex-start;\n",
              "  width: 50%;\n",
              "}\n",
              "\n",
              "#sk-container-id-5 div.sk-parallel-item:only-child::after {\n",
              "  width: 0;\n",
              "}\n",
              "\n",
              "/* Serial-specific style estimator block */\n",
              "\n",
              "#sk-container-id-5 div.sk-serial {\n",
              "  display: flex;\n",
              "  flex-direction: column;\n",
              "  align-items: center;\n",
              "  background-color: var(--sklearn-color-background);\n",
              "  padding-right: 1em;\n",
              "  padding-left: 1em;\n",
              "}\n",
              "\n",
              "\n",
              "/* Toggleable style: style used for estimator/Pipeline/ColumnTransformer box that is\n",
              "clickable and can be expanded/collapsed.\n",
              "- Pipeline and ColumnTransformer use this feature and define the default style\n",
              "- Estimators will overwrite some part of the style using the `sk-estimator` class\n",
              "*/\n",
              "\n",
              "/* Pipeline and ColumnTransformer style (default) */\n",
              "\n",
              "#sk-container-id-5 div.sk-toggleable {\n",
              "  /* Default theme specific background. It is overwritten whether we have a\n",
              "  specific estimator or a Pipeline/ColumnTransformer */\n",
              "  background-color: var(--sklearn-color-background);\n",
              "}\n",
              "\n",
              "/* Toggleable label */\n",
              "#sk-container-id-5 label.sk-toggleable__label {\n",
              "  cursor: pointer;\n",
              "  display: flex;\n",
              "  width: 100%;\n",
              "  margin-bottom: 0;\n",
              "  padding: 0.5em;\n",
              "  box-sizing: border-box;\n",
              "  text-align: center;\n",
              "  align-items: start;\n",
              "  justify-content: space-between;\n",
              "  gap: 0.5em;\n",
              "}\n",
              "\n",
              "#sk-container-id-5 label.sk-toggleable__label .caption {\n",
              "  font-size: 0.6rem;\n",
              "  font-weight: lighter;\n",
              "  color: var(--sklearn-color-text-muted);\n",
              "}\n",
              "\n",
              "#sk-container-id-5 label.sk-toggleable__label-arrow:before {\n",
              "  /* Arrow on the left of the label */\n",
              "  content: \"▸\";\n",
              "  float: left;\n",
              "  margin-right: 0.25em;\n",
              "  color: var(--sklearn-color-icon);\n",
              "}\n",
              "\n",
              "#sk-container-id-5 label.sk-toggleable__label-arrow:hover:before {\n",
              "  color: var(--sklearn-color-text);\n",
              "}\n",
              "\n",
              "/* Toggleable content - dropdown */\n",
              "\n",
              "#sk-container-id-5 div.sk-toggleable__content {\n",
              "  max-height: 0;\n",
              "  max-width: 0;\n",
              "  overflow: hidden;\n",
              "  text-align: left;\n",
              "  /* unfitted */\n",
              "  background-color: var(--sklearn-color-unfitted-level-0);\n",
              "}\n",
              "\n",
              "#sk-container-id-5 div.sk-toggleable__content.fitted {\n",
              "  /* fitted */\n",
              "  background-color: var(--sklearn-color-fitted-level-0);\n",
              "}\n",
              "\n",
              "#sk-container-id-5 div.sk-toggleable__content pre {\n",
              "  margin: 0.2em;\n",
              "  border-radius: 0.25em;\n",
              "  color: var(--sklearn-color-text);\n",
              "  /* unfitted */\n",
              "  background-color: var(--sklearn-color-unfitted-level-0);\n",
              "}\n",
              "\n",
              "#sk-container-id-5 div.sk-toggleable__content.fitted pre {\n",
              "  /* unfitted */\n",
              "  background-color: var(--sklearn-color-fitted-level-0);\n",
              "}\n",
              "\n",
              "#sk-container-id-5 input.sk-toggleable__control:checked~div.sk-toggleable__content {\n",
              "  /* Expand drop-down */\n",
              "  max-height: 200px;\n",
              "  max-width: 100%;\n",
              "  overflow: auto;\n",
              "}\n",
              "\n",
              "#sk-container-id-5 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {\n",
              "  content: \"▾\";\n",
              "}\n",
              "\n",
              "/* Pipeline/ColumnTransformer-specific style */\n",
              "\n",
              "#sk-container-id-5 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
              "  color: var(--sklearn-color-text);\n",
              "  background-color: var(--sklearn-color-unfitted-level-2);\n",
              "}\n",
              "\n",
              "#sk-container-id-5 div.sk-label.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
              "  background-color: var(--sklearn-color-fitted-level-2);\n",
              "}\n",
              "\n",
              "/* Estimator-specific style */\n",
              "\n",
              "/* Colorize estimator box */\n",
              "#sk-container-id-5 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
              "  /* unfitted */\n",
              "  background-color: var(--sklearn-color-unfitted-level-2);\n",
              "}\n",
              "\n",
              "#sk-container-id-5 div.sk-estimator.fitted input.sk-toggleable__control:checked~label.sk-toggleable__label {\n",
              "  /* fitted */\n",
              "  background-color: var(--sklearn-color-fitted-level-2);\n",
              "}\n",
              "\n",
              "#sk-container-id-5 div.sk-label label.sk-toggleable__label,\n",
              "#sk-container-id-5 div.sk-label label {\n",
              "  /* The background is the default theme color */\n",
              "  color: var(--sklearn-color-text-on-default-background);\n",
              "}\n",
              "\n",
              "/* On hover, darken the color of the background */\n",
              "#sk-container-id-5 div.sk-label:hover label.sk-toggleable__label {\n",
              "  color: var(--sklearn-color-text);\n",
              "  background-color: var(--sklearn-color-unfitted-level-2);\n",
              "}\n",
              "\n",
              "/* Label box, darken color on hover, fitted */\n",
              "#sk-container-id-5 div.sk-label.fitted:hover label.sk-toggleable__label.fitted {\n",
              "  color: var(--sklearn-color-text);\n",
              "  background-color: var(--sklearn-color-fitted-level-2);\n",
              "}\n",
              "\n",
              "/* Estimator label */\n",
              "\n",
              "#sk-container-id-5 div.sk-label label {\n",
              "  font-family: monospace;\n",
              "  font-weight: bold;\n",
              "  display: inline-block;\n",
              "  line-height: 1.2em;\n",
              "}\n",
              "\n",
              "#sk-container-id-5 div.sk-label-container {\n",
              "  text-align: center;\n",
              "}\n",
              "\n",
              "/* Estimator-specific */\n",
              "#sk-container-id-5 div.sk-estimator {\n",
              "  font-family: monospace;\n",
              "  border: 1px dotted var(--sklearn-color-border-box);\n",
              "  border-radius: 0.25em;\n",
              "  box-sizing: border-box;\n",
              "  margin-bottom: 0.5em;\n",
              "  /* unfitted */\n",
              "  background-color: var(--sklearn-color-unfitted-level-0);\n",
              "}\n",
              "\n",
              "#sk-container-id-5 div.sk-estimator.fitted {\n",
              "  /* fitted */\n",
              "  background-color: var(--sklearn-color-fitted-level-0);\n",
              "}\n",
              "\n",
              "/* on hover */\n",
              "#sk-container-id-5 div.sk-estimator:hover {\n",
              "  /* unfitted */\n",
              "  background-color: var(--sklearn-color-unfitted-level-2);\n",
              "}\n",
              "\n",
              "#sk-container-id-5 div.sk-estimator.fitted:hover {\n",
              "  /* fitted */\n",
              "  background-color: var(--sklearn-color-fitted-level-2);\n",
              "}\n",
              "\n",
              "/* Specification for estimator info (e.g. \"i\" and \"?\") */\n",
              "\n",
              "/* Common style for \"i\" and \"?\" */\n",
              "\n",
              ".sk-estimator-doc-link,\n",
              "a:link.sk-estimator-doc-link,\n",
              "a:visited.sk-estimator-doc-link {\n",
              "  float: right;\n",
              "  font-size: smaller;\n",
              "  line-height: 1em;\n",
              "  font-family: monospace;\n",
              "  background-color: var(--sklearn-color-background);\n",
              "  border-radius: 1em;\n",
              "  height: 1em;\n",
              "  width: 1em;\n",
              "  text-decoration: none !important;\n",
              "  margin-left: 0.5em;\n",
              "  text-align: center;\n",
              "  /* unfitted */\n",
              "  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n",
              "  color: var(--sklearn-color-unfitted-level-1);\n",
              "}\n",
              "\n",
              ".sk-estimator-doc-link.fitted,\n",
              "a:link.sk-estimator-doc-link.fitted,\n",
              "a:visited.sk-estimator-doc-link.fitted {\n",
              "  /* fitted */\n",
              "  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n",
              "  color: var(--sklearn-color-fitted-level-1);\n",
              "}\n",
              "\n",
              "/* On hover */\n",
              "div.sk-estimator:hover .sk-estimator-doc-link:hover,\n",
              ".sk-estimator-doc-link:hover,\n",
              "div.sk-label-container:hover .sk-estimator-doc-link:hover,\n",
              ".sk-estimator-doc-link:hover {\n",
              "  /* unfitted */\n",
              "  background-color: var(--sklearn-color-unfitted-level-3);\n",
              "  color: var(--sklearn-color-background);\n",
              "  text-decoration: none;\n",
              "}\n",
              "\n",
              "div.sk-estimator.fitted:hover .sk-estimator-doc-link.fitted:hover,\n",
              ".sk-estimator-doc-link.fitted:hover,\n",
              "div.sk-label-container:hover .sk-estimator-doc-link.fitted:hover,\n",
              ".sk-estimator-doc-link.fitted:hover {\n",
              "  /* fitted */\n",
              "  background-color: var(--sklearn-color-fitted-level-3);\n",
              "  color: var(--sklearn-color-background);\n",
              "  text-decoration: none;\n",
              "}\n",
              "\n",
              "/* Span, style for the box shown on hovering the info icon */\n",
              ".sk-estimator-doc-link span {\n",
              "  display: none;\n",
              "  z-index: 9999;\n",
              "  position: relative;\n",
              "  font-weight: normal;\n",
              "  right: .2ex;\n",
              "  padding: .5ex;\n",
              "  margin: .5ex;\n",
              "  width: min-content;\n",
              "  min-width: 20ex;\n",
              "  max-width: 50ex;\n",
              "  color: var(--sklearn-color-text);\n",
              "  box-shadow: 2pt 2pt 4pt #999;\n",
              "  /* unfitted */\n",
              "  background: var(--sklearn-color-unfitted-level-0);\n",
              "  border: .5pt solid var(--sklearn-color-unfitted-level-3);\n",
              "}\n",
              "\n",
              ".sk-estimator-doc-link.fitted span {\n",
              "  /* fitted */\n",
              "  background: var(--sklearn-color-fitted-level-0);\n",
              "  border: var(--sklearn-color-fitted-level-3);\n",
              "}\n",
              "\n",
              ".sk-estimator-doc-link:hover span {\n",
              "  display: block;\n",
              "}\n",
              "\n",
              "/* \"?\"-specific style due to the `<a>` HTML tag */\n",
              "\n",
              "#sk-container-id-5 a.estimator_doc_link {\n",
              "  float: right;\n",
              "  font-size: 1rem;\n",
              "  line-height: 1em;\n",
              "  font-family: monospace;\n",
              "  background-color: var(--sklearn-color-background);\n",
              "  border-radius: 1rem;\n",
              "  height: 1rem;\n",
              "  width: 1rem;\n",
              "  text-decoration: none;\n",
              "  /* unfitted */\n",
              "  color: var(--sklearn-color-unfitted-level-1);\n",
              "  border: var(--sklearn-color-unfitted-level-1) 1pt solid;\n",
              "}\n",
              "\n",
              "#sk-container-id-5 a.estimator_doc_link.fitted {\n",
              "  /* fitted */\n",
              "  border: var(--sklearn-color-fitted-level-1) 1pt solid;\n",
              "  color: var(--sklearn-color-fitted-level-1);\n",
              "}\n",
              "\n",
              "/* On hover */\n",
              "#sk-container-id-5 a.estimator_doc_link:hover {\n",
              "  /* unfitted */\n",
              "  background-color: var(--sklearn-color-unfitted-level-3);\n",
              "  color: var(--sklearn-color-background);\n",
              "  text-decoration: none;\n",
              "}\n",
              "\n",
              "#sk-container-id-5 a.estimator_doc_link.fitted:hover {\n",
              "  /* fitted */\n",
              "  background-color: var(--sklearn-color-fitted-level-3);\n",
              "}\n",
              "</style><div id=\"sk-container-id-5\" class=\"sk-top-container\"><div class=\"sk-text-repr-fallback\"><pre>RandomForestRegressor()</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br />On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class=\"sk-container\" hidden><div class=\"sk-item\"><div class=\"sk-estimator fitted sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-5\" type=\"checkbox\" checked><label for=\"sk-estimator-id-5\" class=\"sk-toggleable__label fitted sk-toggleable__label-arrow\"><div><div>RandomForestRegressor</div></div><div><a class=\"sk-estimator-doc-link fitted\" rel=\"noreferrer\" target=\"_blank\" href=\"https://scikit-learn.org/1.6/modules/generated/sklearn.ensemble.RandomForestRegressor.html\">?<span>Documentation for RandomForestRegressor</span></a><span class=\"sk-estimator-doc-link fitted\">i<span>Fitted</span></span></div></label><div class=\"sk-toggleable__content fitted\"><pre>RandomForestRegressor()</pre></div> </div></div></div></div>"
            ]
          },
          "metadata": {},
          "execution_count": 24
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<Figure size 640x480 with 1 Axes>"
            ],
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAigAAAGdCAYAAAA44ojeAAAAOnRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjEwLjAsIGh0dHBzOi8vbWF0cGxvdGxpYi5vcmcvlHJYcgAAAAlwSFlzAAAPYQAAD2EBqD+naQAAW+NJREFUeJzt3Xl8U2WiP/7POUlO0jRLm+6FAqWliIgIKJsLIJvo9V6Vca6iXlwGHQQXFseLd2Yc585L/InbuOHozAVn4er4nUGvzjhSQMCRTVEUUFtatkLp3iZN0pws5/z+KK2ka9ImTdp+3q8Xr9f0JE0fMkA+Pud5Po+gqqoKIiIiojgixnoARERERG0xoBAREVHcYUAhIiKiuMOAQkRERHGHAYWIiIjiDgMKERERxR0GFCIiIoo7DChEREQUd7SxHkBPKIqC8vJymM1mCIIQ6+EQERFRCFRVRWNjI7KzsyGKXc+R9MuAUl5ejpycnFgPg4iIiHqgrKwMQ4cO7fI5/TKgmM1mAM2/QYvFEuPREBERUSgcDgdycnJaP8e70i8DSsttHYvFwoBCRETUz4SyPIOLZImIiCjuMKAQERFR3GFAISIiorjDgEJERERxhwGFiIiI4g4DChEREcUdBhQiIiKKOwwoREREFHcYUIiIiCjuMKAQERFR3GFAISIiorjDgEJERERxhwGFiIiI4k5YAWXt2rW47LLLYDabkZ6ejhtuuAFFRUVBz/F4PFi2bBlSUlJgMpmwcOFCVFZWBj3n1KlTuO6662A0GpGeno5HHnkEfr+/978bIiIi6jWvX4n1EMILKDt37sSyZcuwd+9eFBYWwufzYd68eXC5XK3PWbFiBd5//32888472LlzJ8rLy3HTTTe1Ph4IBHDdddfB6/Vi9+7dePPNN7Fx40b8/Oc/j9zvioiIiMIWUFRU2D1o9PhiPRQIqqqqPf3m6upqpKenY+fOnbjqqqtgt9uRlpaGTZs24Qc/+AEA4LvvvsOYMWOwZ88eTJ06FR9++CH+5V/+BeXl5cjIyAAAvPbaa3j00UdRXV0NSZK6/bkOhwNWqxV2ux0Wi6WnwyciIqJzZH8AVQ4ZvoACa4IOKSZ9xH9GOJ/fvVqDYrfbAQA2mw0AcODAAfh8PsyZM6f1ORdccAGGDRuGPXv2AAD27NmDcePGtYYTAJg/fz4cDgeOHDnS4c+RZRkOhyPoFxEREUWGw+NDeYMHvkDsb+206HFAURQFDz/8MC6//HJcdNFFAICKigpIkoSkpKSg52ZkZKCioqL1OeeHk5bHWx7ryNq1a2G1Wlt/5eTk9HTYREREdI6iqKhyeFDTKKMXN1SioscBZdmyZTh8+DDeeuutSI6nQ2vWrIHdbm/9VVZWFvWfSURENJA1eQM4Xd8Epxyfm1S0Pfmm5cuX44MPPsCuXbswdOjQ1uuZmZnwer1oaGgImkWprKxEZmZm63P2798f9Hotu3xantOWXq+HXh/5e2FERESDjaqqqHN5YW+K/ULYroQ1g6KqKpYvX47Nmzdj+/btyM3NDXp80qRJ0Ol02LZtW+u1oqIinDp1CtOmTQMATJs2DYcOHUJVVVXrcwoLC2GxWHDhhRf25vdCREREXZD9AZxpaIr7cAKEOYOybNkybNq0Ce+99x7MZnPrmhGr1YqEhARYrVbcc889WLlyJWw2GywWCx544AFMmzYNU6dOBQDMmzcPF154Ie644w48/fTTqKiowE9/+lMsW7aMsyRERERRoKoqGtw+NDT54m6tSWfC2mYsCEKH1zds2IA777wTQHNR26pVq/C///u/kGUZ8+fPx6uvvhp0++bkyZNYunQpduzYgcTERCxevBhPPfUUtNrQ8hK3GRMREYXG61dQ7ZQh+wIhf088bDPuVQ9KrDCgEBERdc/u9qHO7Q1r1kRRVVTYZQRUFTajhLHZFohixxMU4Qrn87tHi2SJiIgofvkCCqobZXjCmDUBgC9P1WPT/jKcrnNDUQGdRkBeuglLZ+Rhen5qlEbbMR4WSERENIA4PD6cqW/qUTh5rrAYx6qdMOq1SDfrkajX4tuzjXhs8yHsLqmJ0og7xoBCREQ0APgDCirszaVrSpirNxRVxab9ZXB7A0g1STBoRYiiAINOg0yLHk45gPU7S6EofbcqhAGFiIion3PJfpxpaILb27PStZJKF8pqXbAYdBAgwCX7W080FgQBSUYdSqucOFLed0fNcA0KERFRP6UoKmpcMpye3rXB2j1e+BQViQJQ6fDA7vHDpNdiRIoRgiBArxFhV1TUub0RGnn3GFCIiIjigKKoOFLuQJ3bG9LumSZvANWNMvxK7w/4sxokKIqKU3VNCJy7PeSU/Who8iHZKEEOKNCJAmxGqdc/K1QMKERERDG2u6QG63eWorTKCV9A7XL3TKSr6uvdXrz1+SnY28zCGHQiDFpNa8nbmCwzxmb3XbUHAwoREVEM7S6pwWObD8Ep+5FslCBpRHgDSuvumSdvHNcaUjy+5lkTX6D3syaqqqLw2yq8+nEJHG3CSbJRhyyLAV5FRYVDhkmvwdIZeRHrQwkFAwoREVGMKIqK9TtL4ZT9yLQYWhvbDaIGmRYRFQ4Z63eWYurIFNibIldVX+Hw4IXCYuw/UR90fUSKEYl6LWoaZVS7vNCJAsZkmWPSg8KAQkREFCNHyh0orXIi2Si1O06mZfdMSWUjdhRVY0Sqsdc/T1FV/N/BcrzxyXE0ndeTkqDTYMmVufjXS7IBIGpNsuFgQCEiIoqROrcXvoAKSdNx64dWECAHVFQ7Pb0OKKdq3XhmSxEOt9kqPHlEMh6eW4BMi6H12pgsc1TO4gkHAwoREVGM2IwSdBoB3oACg6hpva6qKvyKCrcvAK3QvMump/wBBW99VoY/7D0JX+D720MWgxbLZuVjzpj0Tg8DjiUGFCIiohgZm21BXroJ355tRKZFhCAIUFQV/oAKRVXQ6PFhZJoJ+RmJPXr94spGPP1REY5Vu4KuzxqdhuVX5yO5D7cNh4sBhYiIKEZEUcDSGXl4bPMhVDhkmA1aaATAG1DR6PHBKGmwaHIOxDBnODy+AN7cfQLvHDiN89vpU0wSHp49Cpf38YLXnmBAISIiiqHp+an41Q0X4cXtR3Gi2gWfqkInCBiZZsKiyTmYMCw5rNc7WNaAZ7cU40xDU9D1f7k4C/deNRImff/46O8foyQiIhqgPL4Ahqck4skbx6Gk0gW7xwurQUJ+RmJYMydO2Y83dh3D+1+fDbqenWTAqrkFYQedWGNAISIiigFVVVHv9qHh3Pk2oiCgINPUo9faXVqDF7YeRY3z+7NyRAG4edJQLJ4+Agadpovvjk8MKERERH3M61dQ7ZQhn9dF0hP1bi9e3l6Cj4uqg66PTEvEI/NGY3SmuVevH0sMKERERH3I3uRDncvbq0bYzmrqdRoBt08djlsvy4G2k26V/oIBhYiIqA8EFBXVjTLcXn/3T+5CpcOD57cexf7jdUHXx2ZbsHpeAYan9GxLcrxhQCEiIooyt9ePmkYv/ErPD/nrrKbeoBOx5MqR+LdLssPejhzPGFCIiIiiRFVV1Lm8sDf5evU6ndXUXzYiGSva1NQPFAwoREREUSD7A6hulOH193zWxB9Q8PbnZfj9nvY19ffPzMPcCzPisqY+EhhQiIiIIszu9qHO3buFsMWVjVj3URFK29TUzyxorqm3JcZvTX0kMKAQERFFiD/QvH24ydvz7cOyL4A395zEnz8vC66pT5Tw0OxRuGJU/NfURwIDChERDUqKouJIuQN1bi9sRgljsy0QxZ7fLnHKftQ6ZQSUns+afFXWgGcLi3G6Prim/rpxWbjvqpEwGQbPx/bg+Z0SERGds7ukBut3lqK0yglfQIVOIyAv3YSlM/IwPcyD9BRFRY1LhtPT8+3DndXUZ1kNWDWvABP7WU19JDCgEBHRoLK7pAaPbT4Ep+xHslGCpBHhDSj49mwjHtt8CE/eOC7kkOLxNS+E9QV6vhB2T2ktnt9a3K6mfuHEobjr8v5ZUx8JDChERDRoKIqK9TtL4ZT9yLQYWnfAGEQNMi0iKhwy1u8sxdSRKV3e7lFVFQ1uH+rd3k6f050Gtxcvf1yK7d9VBV0fmZqI1fMLcEGmpcevPRAwoBAR0aBxpNyB0ionko1Su+25giAgyahDaZUTR8odGDfU2uFr9PYcHVVVse27Kry8veOa+lsuy4Gun9fURwIDChERDRp1bi98ARVSJwFArxFhV1TUdTIz0ttzdKrO1dTva1NTf2GWBavnF2DEAKmpjwQGFCIiGjRsRgk6jQBvQIFBbL+2Qw4o0IkCbMbgjpHebh9WVBXvf1WO13e1r6n/0RXNNfWaXuwgGogYUIiIaNAYm21BXroJ355tRKZFDLrN07KuZEyWGWOzv1//0ejxodbphdLDWZNTdW48u6UIh84Mnpr6SGBAISKiQUMUBSydkYfHNh9ChUNGklEHvUaEHFDQ4PbBpNdg6Yw8iKKAgKKixinDJfds+7A/oODPn5/Gm3tOBNXUmw1aLIvjmnpREKCPg51DDChERDSoTM9PxZM3jmvtQbErKnSigDFZ5tYelN6WrhVXNuKZj4pRUu0Muj6jIA0PxHFNvdmgQ7JRB20cLNINO6Ds2rUL69atw4EDB3D27Fls3rwZN9xwQ+vjnaXBp59+Go888ggAYMSIETh58mTQ42vXrsV//ud/hjscIiKisE3PT8XUkSntmmQVVUWlw9PjWZP+WlOfIGlgS5Sg18Z+5qRF2AHF5XJh/PjxuPvuu3HTTTe1e/zs2eAWvA8//BD33HMPFi5cGHT9l7/8JZYsWdL6tdlsDncoREREPSaKQtBW4kZP8w6dns6afHW6Ac9uaV9Tf+1FmfjxjLy4rKnXaUSkmCQYpfgbW9gjWrBgARYsWNDp45mZmUFfv/fee5g1axZGjhwZdN1sNrd7LhERUV/zBxTUOL1we3s2a+KS/Xjjk+P4v6/Kg65nWQ1YNbcAE4fHX029RhSQnCjBYtDFeiidiupNpsrKSvztb3/DPffc0+6xp556CikpKZgwYQLWrVsHv7/zPxiyLMPhcAT9IiIi6i2X7MeZhqYeh5O9x2px98bPg8KJKAA3TxqK3y2+NO7CSXMZnYScZGNchxMgyotk33zzTZjN5na3gh588EFMnDgRNpsNu3fvxpo1a3D27Fk899xzHb7O2rVr8cQTT0RzqERENIioqooapxeNHl+Pvr/B7cUrH5diWwc19avmFWBMVvzV1JsMWtiMUlwsgA2FoPa0Dg/NSaztItnzXXDBBZg7dy5eeumlLl/nf/7nf3DffffB6XRCr9e3e1yWZciy3Pq1w+FATk4O7HY7LJb4+0NARETxS/YHUOXo2QF/qqpi+3dVePnjUtibvg83WlHAHVOH45bJ8VdTb9A1L4CNh0MHHQ4HrFZrSJ/fUZtB+eSTT1BUVIS333672+dOmTIFfr8fJ06cwOjRo9s9rtfrOwwuREREoWopYmto8vWoqr7K4cEL245i77G2NfVmrJ4/Ou5q6nUaEbZECYn6+FsAG4qojfp3v/sdJk2ahPHjx3f73IMHD0IURaSnp0drOERENIj15oC/5pr6s3jjk2Nwn1d1b9CKuOfKXNxwyZC4qqnXiM3rTCwGbVwWwYUq7IDidDpRUlLS+vXx48dx8OBB2Gw2DBs2DEDzFM4777yDZ599tt3379mzB/v27cOsWbNgNpuxZ88erFixArfffjuSk+NrMREREUWWoqjtukfEKH+4290+1Ll7dsBfc019MQ6dsQddnzQ8GavmFiDTGj819YIgwGLQIskoxVVg6qmwA8rnn3+OWbNmtX69cuVKAMDixYuxceNGAMBbb70FVVVx6623tvt+vV6Pt956C7/4xS8gyzJyc3OxYsWK1tchIqKBaXdJTWt7qy+gQqcRkJduam1vjbTeHPDXVU39/TPzMC/OauoT9VokGyVI2vha/9IbvVokGyvhLLIhIqLY211Sg8c2H4JT9jd/kGpEeAMK6s+df/PkjeMiGlLcXj+qG3tWVX+0shHrthSjpCq4pv6qglQ8ePWouKqpl7QiUhL1SJBivwA2FHGxSJaIiAhovq2zfmcpnLIfmRZD68yDQdQg0yKiwiFj/c5STB2Z0uvbPaqqotblhaMp/O3Dsi+A3+89ibc/C66pt52rqb8yjmrq+0PRWm8xoBARUVQdKXegtMqJZKPU7rZIc3GYDqVVThwpdwRVz4dL9gdQ3SjD6w9/+/DXpxvwTCc19ffNGAlznASBlnUmyUYp6mt3Yo0BhYiIoqrO7YUvoELqpB9ErxFhV1TUub09ev3ebB92yX789pPjeK+DmvqVcwswKY6aYI2SFrbEgbXOpCsMKEREFFU2owSdRoA3oMAgtl8rIQcU6EQBNmP4azt6M2uy91gtni88imrn90WgogAsnDgUd14+AglxUGwGNPeZpJr6zzqTSGFAISKiqBqbbUFeugnfnm1EpkUMus3TMvsxJsuMsdmhb3rozaxJZzX1uamJWB1HNfUDpc+kpxhQiIgoqkRRwNIZeXhs8yFUOGQkGXXQa0TIAQUN53bxLJ2RF/KaCo8vgBpn+LMmzTX11Xj545J2NfW3Tx2GWycPi4uaekEQYD63zmQg9Jn0FAMKERFF3fT8VDx547jWHhS7okInChiTZQ65B0VVVdS5vEHhIlTVjTKe31rcYU39qnmjkZsaHzX1g22dSVcYUIiIqE9Mz0/F1JEpPWqS9fia15qEe8Cfoqr44OuzeH1XfNfU6zQiUkwSjBI/llvwnSAioj4jikJYW4mVc7t7etJrUlbnxrOFxfj6dJua+mFJWDmvAFnWhLBfM9JEQUCyUYIlYXCuM+kKAwoREcUlt9ePmkYv/Ep4syYBRcWfPy/Dxt3BNfUmfXNN/fyx8VFTb0nQDfp1Jl1hQCEiorgSUFTUumQ4Pf6wv7ekyol1HxXhaNua+lGpeHB2fNTUJ0ga2BIl6LWDa9twuBhQiIgobrhkP2qc4Z+h4/Ur+P2eE3irg5r6B2fn46pRaREeafi4ziQ8fJeIiCjm/AEFtS4vXHL4syaHTtuxbktRu5r6BRdl4sdxUFM/2PtMeooBhYiIYqrR40Odyxv2rEm819Szz6R3GFCIiCgmAoqKGqfco1mTfceba+qrGuOzpp59Jr3HgEJERH3OKftR24O1Jna3D6/sKMHWb4Nr6kekGPHI/NExr6nnOpPI4TtIRER9JqCoqHXKcIY5a9JVTf2iKcNw25TY1tSzzyTyGFCIiKhP9LTXpLOa+jFZZqyOg5p6s0EHWyLXmUQaAwoREUWVoqiodXnR6AmvDVZRVfzt67P4TQc19XdfkYsbJ8S2pt6ga+4zMcR4vctAxYBCRERR09MzdE7Xu/HslmJ81aamfuKwJKycW4DspNjV1GtFETaTBJOeH6HRxHeXiIgirqcnDwcUFe98XoaNe07C6/8+1Jj0WiydmYdrYlhTLwgCkhJ0SDLquM6kDzCgEBFRRMn+AKoc4c+adFZTf+WoVDx4dT5STPpIDjMsJn3ztmFtDBfiDjYMKEREFBGqqqLB7UNDkw+qGvr2Ya9fwR/2nsT/7j8VVFOfbNThodmjcFVB7Grq9ToNUrjOJCYYUIiIqNc8vgBqnHLQbZlQHDptxzNbilDWpqZ+/tgM3D8zL2Y19VpRRHKiLuY1+YMZAwoREfVYT9eauL1+vPHJcbx3MLimPtNiwMq5o3DpCFskhxkyQRBgTdAhKUEHkduGY4oBhYiIeqSnO3T2HqvFC1uDa+oFADdNHIK7r8iNWU29Sa9FcqIU08I3+h4DChERhaWnsyad1dQPTzHikXmjcWF2bGrqJa2IVJOe60ziDAMKERGFrCezJqqqYkdRNV7aXoKGDmrqF00eFpND9TSigORECRauM4lLDChERNStns6aVDfKeGHrUew5Vht0/YJMM1bPK8DINFMkhxkSQRBgMWiRbJS4ziSOMaAQEVGXejJroqgq/n7oLH6z8xhc59XU68/V1N8Uo5r6xHN9JlxnEv8YUIiIqEM97TU5U9+EZwuLcLAsuKZ+wrAkrIpRTb2kFZGSqEeCxHUm/QUDChERtSP7m2dNwuk1CSgq3jlwGht3nwj6vkS9Bktn5GHBRZl9XhHPdSb9FwMKEREFaXB7Ue8Ob9aktMqJdVuKUFwZXFN/RX4qHpydj9Q+rqnnOpP+jwGFiIgANFfOVztlyL5A908+73v+uO8k/nd/GQLn9dTHsqbeKDWvM4nFziCKHAYUIiKC3e1Dndsb1qzJ4TN2PLOlGKfq3EHX54/NwNIZebAk9O1tFZ1GRIpJglHiR9tAEHa83LVrF66//npkZ2dDEAS8++67QY/feeedEAQh6Nc111wT9Jy6ujrcdtttsFgsSEpKwj333AOnM3hakIiIos8XUFDe0IRalxxyOHF7/Xhx21E89NbBoHCSaTHg6YXj8Og1F/RpONGIAlJMeuTYjAwnA0jY/0+6XC6MHz8ed999N2666aYOn3PNNddgw4YNrV/r9cH3Hm+77TacPXsWhYWF8Pl8uOuuu3Dvvfdi06ZN4Q6HiIh6yOHxoc7phRLGrMn+43V4rrC445r6y3P7dJcM15kMbGEHlAULFmDBggVdPkev1yMzM7PDx7799lv84x//wGeffYZLL70UAPDSSy/h2muvxTPPPIPs7Oxwh0RERGHwBxTUOL1we/0hf4+9yYdXd5Si8JvKoOvDU4xYPa8AY7OtkR5ml7jOZOCLylzYjh07kJ6ejuTkZFx99dX41a9+hZSUFADAnj17kJSU1BpOAGDOnDkQRRH79u3DjTfe2O71ZFmGLH+f1h0ORzSGTUQ04IU7a9JZTb1GFHDb5GFYNKVva+q5zmTwiPj/w9dccw1uuukm5ObmorS0FI899hgWLFiAPXv2QKPRoKKiAunp6cGD0Gphs9lQUVHR4WuuXbsWTzzxRKSHSkQ0aPgCCmqcMpq8oe/QqW6U8ettR7G7NLimfnSmGY/0cU29KAhINkqwJGj7vEuFYiPiAeWWW25p/d/jxo3DxRdfjLy8POzYsQOzZ8/u0WuuWbMGK1eubP3a4XAgJyen12MlIhoM7E0+1LvCmzX526EK/GZnabua+rsuH4GFE4f2aU292aCDLVGKSTU+xU7U58hGjhyJ1NRUlJSUYPbs2cjMzERVVfBR236/H3V1dZ2uW9Hr9e0W2hIRUdf8geZek3BmTbqqqV85twBD+rCmPkHSwJYoQa9lPf1gFPWAcvr0adTW1iIrKwsAMG3aNDQ0NODAgQOYNGkSAGD79u1QFAVTpkyJ9nCIiAYFp+xHrVMOKk/rSkBR8f8OnMaGOKip12lE2BIlJOq5zmQwC/v/fafTiZKSktavjx8/joMHD8Jms8Fms+GJJ57AwoULkZmZidLSUvzkJz9Bfn4+5s+fDwAYM2YMrrnmGixZsgSvvfYafD4fli9fjltuuYU7eIiIeklRVNQ4ZTjl0HfolFY78cxHxSiqbAy6fnleCh6aM6rPaupFQUCSUQdrgo7rTAiCGk5tIJp36MyaNavd9cWLF2P9+vW44YYb8OWXX6KhoQHZ2dmYN28e/vu//xsZGRmtz62rq8Py5cvx/vvvQxRFLFy4EC+++CJMptAWXDkcDlitVtjtdlgslnCGT0Q0YLm9ftQ0euFXQjvgr6ua+gdnj8JVo1L7LCiYDFrYjBK0Gm4bHsjC+fwOO6DEAwYUIqLvKYqKWpcXjR5f908+5/AZO57dUoyTMa6pN+ia15kYdFxnMhiE8/nNG3xERP1YkzeAGqcMXyC0WZMmbwC//edxvPvlGZz/X6cZFj1Wzi3AZSNs0RloG1pRhM0kwcR1JtQJ/skgIuqHFEVFndsLR1PosyafnWiuqa90BNfU3zhhCO65om9q6gVBQFKCDklGrjOhrjGgEBH1M+HOmtibfFi/oxRb2tbU24xYPb/vaupN+uZ6eq4zoVAwoBAR9RPhrjVRVRU7i2vw0vajqHfHrqZer9MghetMKEwMKERE/UC4O3RqnDJ+vfUoPu2gpn71vALk9UFNvVYUkZyog9nQNwtuaWBhQCEiimMBRUVtGL0mqqri74cq8NquUrjk2NTUC4IAa4IOSQk6iKynpx5iQCEiilPhtsE219QX42BZQ9D1S3KSsGpuAYYkR7+m3qTXIjlRgo7rTKiXGFCIiOJM4FwbrCvEWZOWmvqNu09AblNT/+Or8nDtuEyoAIornLB7vLAaJORnJEKM4C4aSSsi1aTnOhOKGAYUIqI44pL9qAlj1iSUmvovT9Vj0/4ylNW64FNU6EQBOSmJWDQ5BxOGJfdqvBpRQHKiBAvXmVCEMaAQEcWBcNeaeP0K/rTvJDZ1UFP/wNWjMKOguab+y1P1eK6wGG5vABaDDhaNAF9AxbFqJ54rLMbKuQU9CimCIMBi0CLZKHGdCUUFAwoRUYyFu0PnSLkdz3zUvqZ+3oUZWDozD9ZzNfWKqmLT/jK4vQGkmiQIaA4Seq2AVJOEGqcXm/aXYXxOUli3e4xSc59JX2xRpsGLAYWIKEYCiopalwynJ7RZkyZvAL/753FsblNTn27WY9W89jX1JZUulNW6YDHoWsNJCwECzAYdympdKKl0oSCz+23HOo2IFJMEo8SPDoo+/ikjIooBl+xHrTP0WZPOaupvmDAE91wxosPQYPd44VNUWDQdz45IGgGNqgq7x9vlz9aIApISJFgStKynpz7DgEJE1IfCnTVxNPmwfmcpPjoSXFM/zGbE6nkFuGhI5zX1VoMEndi85kSvbR8svAEVOkGA1SB1+P2CIMB8bp1JtLtTiNpiQCEi6iPhrDVRVRW7jtbgxW3ta+pvnZyD26cM73YNSH5GInJSEnGs2hm0BgUAVKho9PgwMs2E/IzEdt/LdSYUawwoRERRpigqasKYNalxyvj1tqP4tCS4pr4gw4RH5o1GXnpoNfWiIGDR5Bw8V1iMGqcXZoMOkkaAN9AcToySBosm5wQtkNVpmvtM+uJkY6KuMKAQEUVROGtNVFXFh4crsH5ncE29pBVx1/QR+MGk8GvqJwxLxsq5Ba09KI1q822dkWmmoB4UjSggySi17gAiijUGFCKiKPAHFNS6vCG3wZ5paMJzhcX48lRD0PVLcqxYNXd0r2rqJwxLxvicJJRUuto1ybLPhOIVAwoRUYQ5PD7UOb1Q1O7bYAOKir9+cRr/82mbmnpJg/tmNNfUR6KSXhSEdluJeW4OxTMGFCKiCPEFFNQ4ZTR5A90/GcCxaiee2VKM7yqCa+qn56XgodmjkGbWR2OYMOg0sCVKPDeH4hoDChFRBNibfKh3hTZr4vUr2LTvFP60/1RQTX1Sgg4PXJ2PmaPTotI3otOIsCVKSNTzn36Kf/xTSkTUC76AgupGGR5faLMm35Q7sG5LEU7WBtfUz70wA/efV1MfSS0LYC0GFq1R/8GAQkTUQ/YmH+pcXqghzJo0eQP43afHsfmL9jX1K+cWYHKurdPv7SkugKX+jAGFiChM/oCC6jDWmnRWU/9vl2TjR1fmRuVsm0R9czBh0Rr1VwwoRERhCGeHTmc19TnJCXhk/ugua+p7ikVrNFAwoBARhcAfUFDj9MLtDa3XZFdxNX7dQU39LZfl4I6p3dfUh0sQBCQbdbAm6LjOhAYEBhQiom6EM2tS65Tx620l+GdJTdD1cGvqw2GUtEgxsc+EBhYGFCKiToTTa6KqKv5xuAKvdlBTf+e04bj50pyInwjMbcM0kPFPNRFRB8LpNSk/V1P/RZua+vFDrVg1rwBDk40RHZsoCEji7Rwa4BhQiIjOE84OnYCi4q9fnsGGfx6Hp01N/b1XjcR1F2dFpKb+fCaDFjajBC1v59AAx4BCRHROOGtNjte4sO6jonY19VNH2rBiTkHEa+r1Og1SWE9PgwgDChENeuHs0PH6FWzafwqb9p2Cv01N/fKr8zErwjX1WlFEcqIOZkPkG2aJ4hkDChENauHMmnRWUz9nTDqWzcqPaE29IAhISmheZ8IWWBqMGFCIaFAKZ4dOX9fUJ0gapJr03DZMgxoDChENOna3D3Xu0M7Q+fxEHZ4rPIoKhyfo+g1RqKnXiAJSTHqYuG2YCGHH8127duH6669HdnY2BEHAu+++2/qYz+fDo48+inHjxiExMRHZ2dn4j//4D5SXlwe9xogRIyAIQtCvp556qte/GSKirsj+AM40NKHWJXcbTho9Pjz9jyL85C+HgsJJTnICfv3vl+DB2aMiGk7MBh1yko0MJ0TnhP03weVyYfz48bj77rtx0003BT3mdrvxxRdf4Gc/+xnGjx+P+vp6PPTQQ/jXf/1XfP7550HP/eUvf4klS5a0fm02m3v4WyAi6pqqqqh3+2Bv8oU0a7KruBovbi9Bncvbek0UgFsnD4t4Tb1OIyLNrOfuHKI2wg4oCxYswIIFCzp8zGq1orCwMOjayy+/jMmTJ+PUqVMYNmxY63Wz2YzMzMxwfzwRUVg8vgCqG2X4Akq3z611ynhxewk+ORpcUz8q3YRH5o9GfgRr6nl2DlHXor4Cy263N69GT0oKuv7UU08hJSUFEyZMwLp16+D3h3YAFxFRKBRFRY1TRnlDU7fhRFVVfHjoLO7a+HlQOJG0IpZcmYtXb5sY0XCSIGkwNDkBSUaJ4YSoE1G92enxePDoo4/i1ltvhcViab3+4IMPYuLEibDZbNi9ezfWrFmDs2fP4rnnnuvwdWRZhizLrV87HI5oDpuI+rkmbwA1ztBmTcobmvB8YTEOtKmpv3ioFasjXFOvFUXYTBLXmRCFIGp/S3w+H374wx9CVVWsX78+6LGVK1e2/u+LL74YkiThvvvuw9q1a6HXt29fXLt2LZ544oloDZWIBghFUVHjkuH0dD8j21lNvVHS4L4I1dQrqoqSShfsHi+yrQmYNjIF2giuXyEayKISUFrCycmTJ7F9+/ag2ZOOTJkyBX6/HydOnMDo0aPbPb5mzZqgUONwOJCTkxPxcRNR/+X2+lHT6IVf6X7W5HiNC89sKcK3Z6NXU//lqXps2l+G03VuBBQVklZEXroJS2fkYXp+aq9fn2igi3hAaQknR48exccff4yUlJRuv+fgwYMQRRHp6ekdPq7X6zucWSEiCigqap0ynHL3sya+gIJN+07hT21q6q0JOjwQwZr6L0/V47nCYnh8AdgS9ZA0IrwBBd+ebcRjmw/hyRvHMaQQdSPsgOJ0OlFSUtL69fHjx3Hw4EHYbDZkZWXhBz/4Ab744gt88MEHCAQCqKioAADYbDZIkoQ9e/Zg3759mDVrFsxmM/bs2YMVK1bg9ttvR3JycuR+Z0Q04DllP2qdMgJK91uHvz3rwLqPinCio5r6mfmwGiNTUy8AeOfAaXh8AWRZE1oDj0HUINMiosIhY/3OUkwdmcIKe6IuCGoopQDn2bFjB2bNmtXu+uLFi/GLX/wCubm5HX7fxx9/jJkzZ+KLL77A/fffj++++w6yLCM3Nxd33HEHVq5cGfIsicPhgNVqhd1u7/b2ERENPIFzO3RcIcyaNPkC2PDpcfzlQHBNfZpJjxVzR2HqyO5neUMhCALMBi1O1zXh/j8dQKJe22G3SZMvALfsx2/uuBTjhloj8rOJ+otwPr/DnkGZOXNml0VH3eWdiRMnYu/eveH+WCIiAM0Nr3Uub0izJgdONt9qOWsPrqn/t0uysSSCNfVGSQtbogRJK+JIuQO+gAqpk3N09BoRdkVFndvb4eNE1Ix73YioX/AHFNQ4vXB7u581afT48NrOY/jwcEXQ9aHJCVg9rwAXD02KyJh0GhEpJiko6NiMEnQaAd6AAoPYfgZFDijQiQJsRikiYyAaqBhQiCjuhTNr8snRGvx629F2NfW3XJaD/5g2IiI19RpRQHKiBIuh/bqVsdkW5KWb8O3ZRmRaxKBFt6qqosHtw5gsM8Zm8/Y0UVcYUIgoboWz1qTO5cWL245iV5ua+vx0E34SoZp6QRBgTdAhKUHX6QJXURSwdEYeHtt8CBUOGUlGHfQaEXJAQYPbB5Neg6Uz8rhAlqgbDChEFJdC3aGjqio+OlKJV3eUBm01lrQiFk8bjh9emgNNBMKApBWRbjaENAMzPT8VT944Dut3lqK0ygm7okInChiTZWYPClGIGFCIKK6Es9bkrL0JzxUexYGT9UHXLx5qxaq5BcixRaamPskoIdkY3qF+0/NTMXVkCo6UO1Dn9sJmlDA228KZE6IQMaAQUdxweHyoc3qhdLMbMKCoePfgGfzuk/Y19fdeNRL/EoGaeqD57Jx0i77D7cKhEEWBW4mJeogBhYhizhdQUOOU0eQNdPvcvqipB5rbZZONEmc8iGKEAYWIYsru9qHO7e22Q8kXUPC/+0/hj3vb19Qvn5WPqy+ITE29QadBikmCXtuzWRMiigwGFCKKCa9fQbVThuzrftbk27MOPLOlGMdrXEHXI1lTrxEF2BIlmDvYOkxEfY8BhYj6lKqqsDf5UO/2dTtr0uQLYOOnJ/CXL07j/M08ka6pN+m1SDHpI7Lbh4gigwGFiPqMxxdAjVOG97yFrZ354lQ9nt3SQU39+Gz86MpcJOp7/8+XRhSQYtLDFIHXIqLI4t9KIoo6VVVR5/LC3uTr9rlOjx+v7SrF3w+1r6lfNa8A4yNUU2+UtEg1SdB2cmYOEcUWAwoRRZXHF0B1owxfoPtZk3+eq6mvbVNT/++X5WBxhGrqRUGAzdRxTT0RxQ8GFCKKCuXcib2OEGZN6lxevLS9BDuLq4Ou56eb8Mi8AozKMEdkTAmSBqkmPXScNSGKewwoRBRxTd7mtSbdzZqoqoot3zTX1Dd6vm+O1WkELJ42Aj+8dGhEbsEIQvMOHWsCZ02I+gsGFCKKGEVRUevyotHT/axJhd2D5wqL8XmbmvpxQ6xYNa8AwyJUU2+UtEgxSZw1IepnGFCIKCJcsh+1Ti/8StezJgFFxXsHz+C3/zwOjy+6NfUpJikiu32IqO/xby4R9UpAUVHrlINOEu7MiVoXnvmoCN90UFP/8OxRSLcYej0eQRBgMWhZU0/UzzGgEFGPNXp8qHN5EVC6r6l/a38Z/rjvJHyB759rMWjxwNX5uPqC9IjU1BslLWyJUkR2+xBRbDGgEFHYwjnc77sKB575qBjH2tTUz74gHctm5SHJKPV6PDpN8+0co8R/0ogGCv5tJqKwhHq4n8cXwIYOaupTTRJWzCnAtLze19RrRAFJRu7OIRqIGFCIKCSyv7lwrTc19f86PhtLIlRTbzboYEuUeH4O0QDFgEJEXVIUFfXu+KmpN+g0SDFJ0Gs1vX4tIopfDChE1Cm3t3nrcCg19Z+W1OCFre1r6n94aQ4WTxsOva53gUIjCkhOZEU90WDBgEJE7QQUFbUuGU5P91uH61xevLy9BDva1tSnmbB6fgEKIlBTb9JrkWLS83YO0SDCgEJEQUItXFNVFYXnauodUaqp5+4cosGLf+uJCEB4hWsVDg+eLyzGZyfa1tRbsGre6IjU1FsSdLCxbI1o0GJAIaKQZ00UVcW7X5bjt/88FlRTn6DT4N6rcnH9+Oxe19RrRRFpZj0SJC6CJRrMGFCIBrFw1pqcrHXhmS3FOFLuCLo+JdeGh+eMQkYEaurNBh1SEjlrQkQMKESDltvrR01j97MmvoCCtz4rwx/3Rq+mXqcRkWrirAkRfY8BhWiQCWetSVFFI9ZtKcKx6uCa+qsvSMfyCNXUWxOaC9cicRYPEQ0cDChEg0ioh/t5fAFs3H0C/+9A+5r6h+eMwvS81F6PRdI2rzVh4RoRdYQBhWgQCOdwvy9P1ePZwmKUNwTX1F8/PgtLrhwJUy9r6gVBgM0owWpk4RoRdY4BhWiAs7t9qHd7oXRzuJ9T9uP1Xcfwwddng64PSUrA6nkFGJ+T1OuxGCUtUkwSdL3sRyGigY8BhWiA8vqbZ008vu5nTT4tqcEL246i1hm9mnpbogQza+qJKEQMKEQDjKqqsDf5UO/2Qe1m1qTe3VxT/3FRcE19XloiHpk/utc19YIgwGLQIrkPC9cURcWRcgfq3F7YjBLGZlu4bZmoHwp7nnXXrl24/vrrkZ2dDUEQ8O677wY9rqoqfv7znyMrKwsJCQmYM2cOjh49GvScuro63HbbbbBYLEhKSsI999wDp9PZq98IEQGyP4Byuwd1Lm+X4URVVWz5phJ3bfgsKJzoNAJ+dEUu1t82sdfhxChpMSQpASkmfZ8FhN0lNVi8YT/u+8PnWP3nr3DfHz7H4g37sbukpk9+PhFFTtgBxeVyYfz48XjllVc6fPzpp5/Giy++iNdeew379u1DYmIi5s+fD4/n+wV3t912G44cOYLCwkJ88MEH2LVrF+69996e/y6IBjlVVdHg9qK8wQO5m1s6FQ4P1vz1EJ768LugM3TGDbHgjf+4FIumDOvVGTpaUUSm1YBMqwGStu/WmuwuqcFjmw/h27MOJOq1SDfrkajX4tuzjXhs8yGGFKJ+RlC7mwPu6psFAZs3b8YNN9wAoPkfyezsbKxatQqrV68GANjtdmRkZGDjxo245ZZb8O233+LCCy/EZ599hksvvRQA8I9//APXXnstTp8+jezs7G5/rsPhgNVqhd1uh8Vi6enwiQYE2R9AjdPbbTBRVBXvHSzHG59Er6Y+Vk2wiqJi8Yb9+PasA5kWQ1CniqqqqHDIGJNlxpt3TebtHqIYCufzO6L/eXP8+HFUVFRgzpw5rdesViumTJmCPXv2AAD27NmDpKSk1nACAHPmzIEoiti3b1+HryvLMhwOR9AvosFOVVXUu0KbNTlV68bDbx3ES9tLgsLJ5Fwb/ufOS/FvlwzpVThpmTVJM/fd7ZzzHSl3oLTKiWRj+8I3QRCQZNShtMrZrqafiOJXRBfJVlRUAAAyMjKCrmdkZLQ+VlFRgfT09OBBaLWw2Wytz2lr7dq1eOKJJyI5VKJ+TfYHUN0ow+vvuqbef66m/g8d1NQvm5WPOWN6X1NvMmiRmhibYNKizu2FL6BC6uTWlF4jwq6oqHN7O3yciOJPv9jFs2bNGqxcubL1a4fDgZycnBiOiCg2mtea+NDQ1P0Onc5q6meNTsPyq/OR3Mua+ng6P8dmlKDTCPAGFBjE9uORAwp0YnNBHBH1DxENKJmZmQCAyspKZGVltV6vrKzEJZdc0vqcqqqqoO/z+/2oq6tr/f629Ho99Hp9JIdK1O94fAHUOLufNfH4Anhz9wm806amPsUk4eHZo3B5fu9q6gVBQFKCDklGXdycnzM224K8dBO+PduITIvYbg1Kg9uHMVlmjM3mmjWi/iKia1Byc3ORmZmJbdu2tV5zOBzYt28fpk2bBgCYNm0aGhoacODAgdbnbN++HYqiYMqUKZEcDtGAoKrNh/uVNzR1G04OljVgye8P4O3Pg8PJ9RdnYcOdl/U6nBh0GgxJSkBynB3uJ4oCls7Ig0mvQYVDRpMvAEVR0eQLoMIhw6TXYOmMPC6QJepHwp5BcTqdKCkpaf36+PHjOHjwIGw2G4YNG4aHH34Yv/rVrzBq1Cjk5ubiZz/7GbKzs1t3+owZMwbXXHMNlixZgtdeew0+nw/Lly/HLbfcEtIOHqLBxONrXmviC3QdTLqqqV81rwCX9LKmXhQEJCdKsCbEbxPs9PxUPHnjOKzfWYrSKifsigqdKGBMlhlLZ+Rhei/DGRH1rbC3Ge/YsQOzZs1qd33x4sXYuHEjVFXF448/jtdffx0NDQ244oor8Oqrr6KgoKD1uXV1dVi+fDnef/99iKKIhQsX4sUXX4TJZAppDNxmTAOdcm5Bp6PJ1+1zd5fW4Pmt7Wvqb540FIunj4ChlzX1iXotUhKlXnWj9CU2yRLFr3A+v3vVgxIrDCg0kLm9ftQ0euFXup416aymfmRaIh6ZNxqjM3vXBKsRBaSY9CGfXsxgQETdCefzu1/s4iEaDAKKilqXDOd57a4dUVUVhd9W4dWPS4KaYHUaAXdMHY5bLsvp9WyHUdIi1RT6rMnukprWWyu+gAqdRkBeuom3VoioxxhQiOKAS/aj1tn9rEmFw4MXCoux/0R90PWx2RY8Mm80hqUYezUOQWg+dTictSYtFfNO2Y9kowRJI8IbUFor5p+8cRxDChGFjQGFKIYCSvMOHafc9ayJoqr4v4PleOOT42g6rzU2QafBkitz8a+X9L6mXq/TIM2kD+v8HEVRsX5nKZyyP6hi3iBqkGkRUeGQsX5nKaaOTOHtHiIKCwMKUYw0enyoc3kRULpeBnaq1o1nthThcJua9skjkvHw3AJkWgy9GocgCEg26pDUgxKzcCrmxw219mqcRDS4MKAQ9TF/QEGN0wu3t+tZE39Awdufl+H3e9rX1N8/Kx9zI1BTr9OISLfoodf2bKcPK+aJKFoYUIj6kMPjQ53TC6WbzXPFlY1Y91ERSkOoqVdUFSWVLtg9XlgNEvIzEkO63WNN0MHWy8I1VswTUbQwoBD1AV9AQY1TRpO361OHZV8Ab+45iT9/XhZSTf2Xp+qxaX8Zympd8J0rJstJScSiyTmYMCy5w5+hFZtnTXrbjwKwYp6Ioqd/NC8R9WN2tw+n65u6DSdflTXgR78/gLc+Cw4n143ruKb+y1P1eK6wGMeqnUiQmsvUEiQtjlU78VxhMb48VY+2TAYthiYnRCScAKyYJ6Lo4QwKUZR4/QqqnTJkX9fBxCn78cauY3i/TU19dpIBq+YWdDgToqgqNu0vg9sbQKpJgoDmAKDXCkg1SahxerFpfxnG5yRBFISwS9fCwYp5IooGBhSiCGu5tdHQ5EN3Rc27S2vwwtajqAmzpr6k0oWyWhcsBl1rOGkhQIDZoENZrQsllS6MH2ZFmkkf1ar66fmpmDoyhU2yRBQxDChEERTq4X4Nbi9e/rgU27+rCroeak293eOFT1Fh0XQcACSNgEZVhQIVWdaE8H4TPSSKArcSE1HEMKAQRUA4NfXbvqvCy9t7V1NvNUjQiQJ8ARV6bfuQ4lNUGDQicpJ71yxLRBQrDChEvRRq4Vqlw4Pntx7F/uN1QdfHZluwel4Bhqckhvwz8zMSkZOSiGPVzqA1KBCabxE5XX5cmG3h7hki6rcYUIh6KNStw4qq4v2vyvH6ruCaeoNOxI+uGIkbJoRfUy8KAhZNzsFzhcWocXphNuig14hQVBV1TX6YDVruniGifo0BhShMqqrC3uRDvbv7RbCn6tx4dksRDp0Jrqm/bEQyVvSypn7CsGSsnFuATfvLcLrODbfXD0kjcvcMEQ0IDChEYfD4AqhxyvD6u14E6w8o+PPnp/HmnhNRq6kHgMm5KVhwURZKq13cPUNEAwoDClEIlHPnyTiafN0+t7iyEc98VIySamfQ9RkFaXjg6nzYEiNT+2426JCSKHH3DBENSAwoRN1wyX7UOr3wK13PmnRaU58o4aHZo3DFqMjcctGIAlJNeiRGoXSNiChe8F84ok74AgpqQzh1GAC+Ot2AZ7cU43R9U9D168Zl4b6rRsJkiMxfNaOkRZpZDw1v4RDRAMeAQtRGOItgXbIfr39yDO9/FVxTn2U1YNW8Akzs5MC+cAmCgBSTBItBF5HXIyKKdwwoROcJtQkWAPaU1uKFrUdR7ZRbr4kC8INJQ3FnFzX14dLrNEgz6SFpebYnEQ0eDChECL0JFuiipj41EavnF+CCzMiVoyUZJSQbdRHZ8UNE1J8woNCg5/D4UB9CE2xXNfW3TxmOWybnQBehA/m0oog0sx4JUmRmYYiI+hsGFBq0ZH8ANU4vZF/XTbAAUHWupn5fm5r6C7MsWD2/ACPCqKnvTqJei1QTF8IS0eDGgEKDjqKoqHd7YQ+h06S5pv4s3vjkGNzetjX1ufi3S4ZELEgIggBbogRrAhfCEhExoNCg4vb6UdPYfacJ0FJTX4xDZ+xB1y8dnoyH54yC0xPAF6fqYTVIyM9IDPs8nfPpNCLSLXrotbylQ0QEMKDQIOEPKKh1eeGSu18E21lNvdmgxf0z85BmkvD81qMoq3XBp6jQiQJyUhKxaHIOJvRgW7HZoGs+kZgLYYmIWjGg0IDn8PhQ5/RC6abTBACOVjZiXQc19VcVpOLBq0fhZK0LzxUWw+0NwGLQwaIR4AuoOFbtxHOFxVg5tyDkkCIKAlLNepjYCEtE1A7/ZaQBy+tXUOOU4QlhEazsC+D3e0/i7c+Ca+pt52rqrxyVCkVVsfbDMri9geYZDzTPeOi1AlJNEmqcXmzaX4bxOUnd3u7R6zRIN+sjtuuHiGigYUChASecJlgA+Pp0A57poKb+2osycd+MkTCfa28tqXShrNYFi0HXGk5aCBBgNuhQVutCSaULBZmmTn+eNUEHWyJv6RARdYUBhQYUjy+AGqcMr7/7RbAu2Y83PjmO//uqPOh6ltWAVXMLMHF48K0au8cLn6LCouk4WEgaAY2qCrvH2+HjGlFAmlkPo8S/dkRE3eG/lDQghLN1GAD2HqvF84Xta+oXThyKOy8fgYQOauqtBgk6sXnNiV7bPqR4Ayp0ggCrQWr3mOHcLR0tb+kQEYWEAYX6vSZv86xJKOfnNLi9eOXjUmxrU1Ofm5qI1fMKMCar85r6/IxE5KQk4li1M2gNCgCoUNHo8WFkmgn5GcGlbUlGCbbE9qGFiIg6x4BC/VY45+eoqort31Xh5Y9Lg2ZZtKKAO6aGVlMvCgIWTc7Bc4XFqHF6YTboIGkEeAPN4cQoabBock7rAlnW1RMR9RwDCvVLTtmPWqfc7fk5QHNN/QvbjmLvsbY19Wasmjcauamh19RPGJaMlXMLsGl/GcpqXWhUm2/rjEwzBfWgJEgapJsNrKsnIuqhiAeUESNG4OTJk+2u33///XjllVcwc+ZM7Ny5M+ix++67D6+99lqkh0IDkD+goMbphdvb/axJpzX1WhE/urLnNfUThiVjfE4SSipdsHu8QU2ygiAg2ahDkpG3dIiIeiPiAeWzzz5DIPD9h8Hhw4cxd+5c3Hzzza3XlixZgl/+8petXxuNxkgPgwYge1PzqcOhFK6V1bnxTAc19ZOGJ2Pl3FHIsib0aiyiILTbSqwVm+vqDR0ssCUiovBEPKCkpaUFff3UU08hLy8PM2bMaL1mNBqRmZkZ6R9NA1Q4hWsBRcWfPy/Dxt3BNfUmvRZLZ+bhmrEZUekfMUpapJl5AjERUaREdQ2K1+vFH//4R6xcuTLoQ+FPf/oT/vjHPyIzMxPXX389fvazn3U5iyLLMmT5++2gDocjmsOmOBFu4drRykas21KMkqqOa+qjsZNGEATYjBKsRp5ATEQUSVENKO+++y4aGhpw5513tl5btGgRhg8fjuzsbHz99dd49NFHUVRUhL/+9a+dvs7atWvxxBNPRHOoFGdkfwDVjaEVrnn9Cn6/5wTe6qCm/sHZ+bhqVFrn39wLPIGYiCh6BDWU/zTtofnz50OSJLz//vudPmf79u2YPXs2SkpKkJeX1+FzOppBycnJgd1uh8XSeW8F9T+qqqLB7UNDU2izJodO27FuS1G7mvoFF2Xix+fV1EeayaBFaqIeIm/pEBGFzOFwwGq1hvT5HbUZlJMnT2Lr1q1dzowAwJQpUwCgy4Ci1+uh1+sjPkaKL+HMmrhkP377yXG8F2JNfaSIgoAUkxS14ENERM2iFlA2bNiA9PR0XHfddV0+7+DBgwCArKysaA2F4ly4syZ7j9Xiha1HUdUYek19JEhaEelmAyQt6+qJiKItKgFFURRs2LABixcvhlb7/Y8oLS3Fpk2bcO211yIlJQVff/01VqxYgauuugoXX3xxNIZCcS6cWZN6txf/34dF2H8iuHAtlJr63uIJxEREfSsqAWXr1q04deoU7r777qDrkiRh69ateOGFF+ByuZCTk4OFCxfipz/9aTSGQXFMVVXUu32whzBroqoq/ufT43j7s9Pwn7cKVgAwb2wGVs4t6Lamvqd4AjERUWxEdZFstISzyIbij8fXPGsSyuF+1Y0ynnj/CL452xh0XdKIMOhEmA1arJxb0FoxH0lGSYtUk8QTiImIIiQuFskStaUoKmpdXjR6fN0/V1Xxwddn8fqu4Jp6AUCqSUJSgg4QgBqnF5v2l2F8TlLrIX29xW4TIqLYY0ChPuGS/ah1euFXup81Katz49nCYnx9Orim3qjTIMOiD7qdYzboUFbrQkmlq131fE+w24SIKD4woFBUhXO4X2c19QKANLMEq0HXbpGqpBHQqKqwe7y9HqvZoEOqiQthiYjiAQMKRY3d7UO9O7TD/UqqnFj3URGOtqmpn5CThFO1LiTotB0GB29AhU4QYDX0vMae3SZERPGHAYUizuMLoNblhRzC4X6d1dQnG3V4aPYoXDEqFY/+5RCOVTubZzfwfUhRoaLR48PINBPyMxJ7NFZ2mxARxScGFIqYgKKiLsRFsEDoNfWLJufgucJi1Di9MBt0kDQCvIHmcGKUNFg0OadHC2R5S4eIKH4xoFBENHp8qHN5EVC6v53j9vrxxifH8d7B9jX1K+cWYFKbmvoJw5Kxcm4BNu0vQ1mtC41q822dkWkmLJqcE/YWY1EQkGrWw6TnH38ionjFf6GpW4qi4ki5A3VuL2xGCWOzLa2H5Hn9CmpdMpq83d/OATquqRcALJw0BHddnttpTf2EYckYn5OEkkoX7B4vrAYJ+RmJYc+c6HUapJv1USt2IyKiyGBAoS7tLqnB+p2lKK1ywhdQodMIyEs34cdXjcTYIVbUu0M7P8fu9uGVHSXY+m1V0PURKUasnjcaF2Z3X7gnCkKvthInGSUkG9vvBCIiovjDgEKd2l1Sg8c2H4JT9iPZKEHSiPAGFHxT7sCjf/kaK0JocFVVFR8XVePl7SVoaPp+bYpWFHDblGFYNGVY1GcztGJzt4khSocIEhFR5DGgUIcURcX6naVwyn5kWgwQBAGqqkIrCrAl6kJqcK1ulPHC1qPYc6w26PoFmWY8Mn80clN7tvMmHCaDFqmJ+tZbUkRE1D8woFCHjpQ7UFrlRLKxeZeLoqjwKypUVYUAocsGV0VV8bdzNfWu89am6LUi7r58BG6aOBSaKAcGjSggxcSFsERE/RX/9aYO1bm9zWtORAG+gAKlze6czhpcT9e78eyWYnzVpqZ+4rAkrJxbgOykhKiPPUHSIM2k5yF/RET9GAMKdchmlKARAZc3AH0HJWZtG1wDiop3Pi/Dxj0n4fV/f95Ool6D+2fk4ZqLMqO+OFUQBNgSJVgT2AhLRNTfMaBQOx5fAEkJOgxJNobU4Fpa5cTTHdTUX5Gfiodm5yPFpI/6mPW65lkTNsISEQ0MDCjUKqCoqHXJcHqaD/brrsH15klDsOHT5pr68wvaWmrqrypI65Nxc/swEdHAw4ASp7oqR4sGp+xHrVMOChpdNbhOG2nDKx+XoqxNTf01Y5tr6i19cJtFK4pIM+uRIHH7MBHRQMOAEoc6K0dbOiMP0/NTI/qz/AEFtS4vXLK/w8fbNrjqNRp8XFyFVz4uxfnLZjMtBqyYOwqXjbBFdHydMUpapJn1Ud8NREREsSGoodSAxhmHwwGr1Qq73Q6LpfsG0v6ks3K0ercPJr0GT944LmIhxeHxoT7E83MAYN/xWjxf2L6m/qaJQ3D35bl9MpMhCAKSjTokGaWo/ywiIoqscD6/OYMSRzoqRwMAg6hBpkVEhUPG+p2lmDoypVe3e7x+BTVOGR5faOfn2Jt8eHVHKQq/qQy6PjzFiNXzCjA229rjsYRDp2m+pcNGWCKigY8BJY60LUc7nyAISDLqUFrlxJFyB8YNDT8UqKqKercP9qbQzs9RVRU7iqrxUpuaeo0o4LbJzTX1fbVrxqTXItXERlgiosGCASWOtJSjSZ0UjOk1IuyKijq3t8PHu+KU/ah3eeELKN0/Gc019b/edhS7S4Nr6kdnmvHIvAKMTOv5oX3hEAQBKSYJFgO7TYiIBhMGlDhiM0rQaQR4AwoMYvvbGHJAgU4UYAtj/YVL9qPe7Q0qT+uKoqr4+6Gz+M3O2NXUt9Bpmg/502t5S4eIaLBhQIkjY7MtyEs34duzjci0iEG3eVRVRYPbhzFZZozN7n5hsMcXQK3LCznEdSYAcKa+Cc8WFuFgWXBN/YRzNfVD+qCmvoXZoGsuiGO3CRHRoMSAEkdEUcDSGXl4bPMhVDhkJBl10GtEyAEFDed28SydkdflOoy2ZWuhCCgq3jlwGht3n2hXU790Rh4W9EFNfQtREJBq5iF/RESDHT8F4sz0/FQ8eeO41h4Uu9J8YN+YLHO3PSjhbhsGgNIqJ9ZtKUJxZXBN/eX5KXho9iik9kFNfQu9ToN0sx46HvJHRDToMaDEoen5qZg6MiXkJlnZH0Ct0xvytmGgeavxH/edxP/ub19T/8DVozCjILVPb69YE3SwJfKWDhERNWNAiVOiKHS7lVg5t6PHcd4W4FAcPmPHM1uKcarOHXR9/tgMLJ2R1yc19S00ooA0sx5GiX8UiYjoe/xU6Kd6cjvH7fXjt58cx3sHy2NaU98iQWo+gVjLWzpERNQGA0o/E24LbIv9x+vwXGFxu5r6GycMwT1X9E1NfevPZV09ERF1gwGln2jZZtwQYgtsC3uTD+t3lGJL25p6mxGr5/ddTX0LrdjcbcK6eiIi6goDSj/g8QVQ3SiH3AILNAeancXNNfX17uCa+kWTc3DblOF9VlPfIvFcXT1PICYiou4woMSxgKKizuVFoye8RbA1Thm/3noUn7atqc8wY/X8AuT1UU19C0EQYEuUYO3DxbdERNS/MaDEqZ4sglVVFX87VIHf7CqFSw6uqb/r8hFY2Ic19S1YV09ERD3BgBJnZH8ANc7wKuqBlpr6Yhwsawi6fklOElbN69ua+hYmgxZpJj27TYiIKGwRX4Twi1/8AoIgBP264IILWh/3eDxYtmwZUlJSYDKZsHDhQlRWVnbxioNDQFFR3SjjTH1TWOEkoKh4+7My/Oj3nweFk0S9BivnFuDZmy/u83AiCgLSLQakmw0MJ0RE1CNRmUEZO3Ystm7d+v0P0X7/Y1asWIG//e1veOedd2C1WrF8+XLcdNNN+PTTT6MxlH7B3uRDgzu82zkAUFrtxDMfFaOosjHoeixq6luwrp6IiCIhKgFFq9UiMzOz3XW73Y7f/e532LRpE66++moAwIYNGzBmzBjs3bsXU6dOjcZw4pbHF0CNUw46oC8UXr+CP+07iU1xUlPfgnX1REQUKVEJKEePHkV2djYMBgOmTZuGtWvXYtiwYThw4AB8Ph/mzJnT+twLLrgAw4YNw549ezoNKLIsQ5a/LxhzOBzRGHaf6cmJwy2OlNvxzEfFOBkHNfUtWFdPRESRFvFPlClTpmDjxo0YPXo0zp49iyeeeAJXXnklDh8+jIqKCkiShKSkpKDvycjIQEVFRaevuXbtWjzxxBORHmpM2Juad+coYZStAUCTN4Df/vM43v3yTFBNfYZFj5VzC/q8pr4F6+qJiCgaIh5QFixY0Pq/L774YkyZMgXDhw/Hn//8ZyQk9Gyx5po1a7By5crWrx0OB3Jycno91r7U09s5APDZieaa+kpH7Gvqz5dslJCcyLp6IiKKvKjPySclJaGgoAAlJSWYO3cuvF4vGhoagmZRKisrO1yz0kKv10Ov7/sFn5HgCyioc3nhksO/neNo8mH9zlJ8dCR4l9MwmxGr5xXgoiF9W1PfgnX1REQUbVGfl3c6nSgtLUVWVhYmTZoEnU6Hbdu2tT5eVFSEU6dOYdq0adEeSp9SFBW1Thmn65vCDieqqmJHUTXu2vhZUDjRiALumDoMr98xKWbhJFGvxZDkBIYTIiKKqojPoKxevRrXX389hg8fjvLycjz++OPQaDS49dZbYbVacc8992DlypWw2WywWCx44IEHMG3atAG1g6fR40NdmC2wLWqcMn697Sg+LYmPmvoWrKsnIqK+FPGAcvr0adx6662ora1FWloarrjiCuzduxdpaWkAgOeffx6iKGLhwoWQZRnz58/Hq6++GulhxITXr6DWJaPJG14LLNA8a/L3QxV4rU1NvaQVcef0Ebh5Ut/X1LdgXT0REfU1QVXD3E4SBxwOB6xWK+x2OywWS8ReV1FUHCl3oM7thc0oYWy2BWIIoUBRVDQ0+WBv8qEnb+eZhiY8V1iML081BF2/JMeKVXNHY0hy39fUtzAZtEhN1If0PhAREXUlnM9vFlecs7ukBut3lqK0yglfQIVOIyAv3YSlM/IwPT+10+9zeHxocPngV8LfnRNQVPzli9PY8OkJyOft7kmUNLhvxkhcNy4rZqVnoiAgxSTBbOAtHSIi6nsMKGgOJ49tPgSn7EeyUYKkEeENKPj2bCMe23wIT944rl1IafIGUOvq2bZhADhW7cS6LcUoqgiuqZ+e11xTn2aO3a4lSSsi3WyApGW3CRERxcagDyiKomL9zlI4ZT8yLd8fbmcQNci0iKhwyFi/sxRTR6ZAFIVebRsGuqupz8eMgrSYVsVbEnRIYV09ERHF2KAPKEfKHSitciLZ2P5DWRAEJBl1KK1y4tAZO3Jsxh6vMwGAw2fseHZL+5r6uRdm4P6ZeTHdIaMRBaSa9EjUD/o/EkREFAcG/adRndsLX0CF1ElVu14joj6goLiyEWZDz96uJm8Av/vncWxuU1Ofbm6uqZ+cG5ua+haGcycQs66eiIjixaAPKDajBJ1GgDegwCAGb6NVVBUurx8aAGZ9z2Y3Oqupv2HCENxzxYiYH7DHunoiIopHgz6gjM22IC/dhG/PNiLTIkIQBKiqioCiwq8osDf5MDLNhPyMxLBeN15r6luwrp6IiOLZoA8ooihg6Yw8PLb5ECocMqwJWogQIAcUNHp8MEoaLJqcAzHERaOqqmLX0Rq8uO0o6t2+1usaUcCtk3Nw+5ThMd8dY5S0SDPrY1b8RkRE1J1BH1AAYHp+Kp68cRzW7yzF0cpGyAEFOkHAyDQTFk3OwYRhySG9Tmc19QUZJjwybzTy0mNTU99CEATYjBKsRnabEBFRfGNAOWd6fiqmjkzBZyfqcKLWBatBQn5GYkgzJ6qq4sPDFVi/M/5q6lvoNCLSzLylQ0RE/QMDynlEUcCF2ZawStLKG5rwbJzW1LdgXT0REfU3DCg9FFBU/PXLM/iffx7vsKb+2nFZIa9biRZREJBq1sPEbhMiIupn+MnVA8drXFj3URG+i8Oa+hb6c90mOnabEBFRP8SAEgavX8Gm/aewad8p+M+rqU9K0OHB2bGvqW8dj1FCslEXF2MhIiLqCQaUEH1T7sC6LUU4WRtcUz/vwgwsjXFNfQt2mxAR0UDBgNKNJm8Av/v0ODZ/EZ819S1Mei1STVwIS0REAwMDShc+P1GH5wqPosLhab0mAPi3S7LxoytzY15TDzQvhE0xSTAbYj+DQ0REFCmx/4SNQ53V1OckJ+CR+aNjXlPfggthiYhooGJAaaPwm0r89wfftKupv+WyHNwxNfY19S24EJaIiAYyBpRzqhwe/Oy9w+1mTUalm/DI/NHIj3FNfQut2NwImyBxISwREQ1cDCjnVDg8KPzm+3ASTzX1LRLPLYSNl/EQERFFS3zcr4gDFw9NwpIrRwIAxg+14rf/MQm3XJYTF2GgpRE2w2KIi/EQERFFG2dQzvPwnAIMsxkxZaQt5jX1LfQ6DdJM+rhZ+0JERNQX+Kl3ngRJg3+9JDtuwkmSUUK21cBwQkREgw5nUOIQF8ISEdFgx4ASZ7gQloiIiAElbgjnGmEtbIQlIiJiQIkHklZEuplrTYiIiFowoMSYNUEHW6LERlgiIqLzMKDECBfCEhERdY4BJQa4EJaIiKhrDCh9iAthiYiIQsOA0ke4EJaIiCh0DCh9gAthiYiIwsOAEkVaUUSqWYJR4ttMREQUjojfb1i7di0uu+wymM1mpKen44YbbkBRUVHQc2bOnAlBEIJ+/fjHP470UGLKKGkxJDmB4YSIiKgHIh5Qdu7ciWXLlmHv3r0oLCyEz+fDvHnz4HK5gp63ZMkSnD17tvXX008/HemhxETzQlg9Mq0G7tIhIiLqoYj/5/0//vGPoK83btyI9PR0HDhwAFdddVXrdaPRiMzMzEj/+JjiQlgiIqLIiPonqd1uBwDYbLag63/605+QmpqKiy66CGvWrIHb7Y72UKLKmqDDkKQEhhMiIqIIiOoCCUVR8PDDD+Pyyy/HRRdd1Hp90aJFGD58OLKzs/H111/j0UcfRVFREf761792+DqyLEOW5davHQ5HNIcdFo0oIM2s51oTIiKiCIrqp+qyZctw+PBh/POf/wy6fu+997b+73HjxiErKwuzZ89GaWkp8vLy2r3O2rVr8cQTT0RzqD1ilLRIM7MRloiIKNKidj9i+fLl+OCDD/Dxxx9j6NChXT53ypQpAICSkpIOH1+zZg3sdnvrr7KysoiPNxxcCEtERBRdEZ9BUVUVDzzwADZv3owdO3YgNze32+85ePAgACArK6vDx/V6PfR6fSSH2WOStvmQP72Wh/wRERFFS8QDyrJly7Bp0ya89957MJvNqKioAABYrVYkJCSgtLQUmzZtwrXXXouUlBR8/fXXWLFiBa666ipcfPHFkR5ORFkSdEhhIywREVHUCaqqqhF9wU4+vDds2IA777wTZWVluP3223H48GG4XC7k5OTgxhtvxE9/+lNYLJaQfobD4YDVaoXdbg/5e0LV6PGhulEOusaFsERERL0Xzud3VG7xdCUnJwc7d+6M9I+NGi6EJSIi6nucEuiEIAiwJUqwJuhiPRQiIqJBhwGlAzqNiHQLF8ISERHFCgNKGwadBkOTtVwIS0REFEMMKG3oNKyqJyIiijV+GhMREVHcYUAhIiKiuMOAQkRERHGHAYWIiIjiDgMKERERxR0GFCIiIoo7DChEREQUdxhQiIiIKO4woBAREVHcYUAhIiKiuMOAQkRERHGHAYWIiIjiDgMKERERxR0GFCIiIoo72lgPoCdUVQUAOByOGI+EiIiIQtXyud3yOd6VfhlQGhsbAQA5OTkxHgkRERGFq7GxEVartcvnCGooMSbOKIqC8vJymM1mCIIQ6+G043A4kJOTg7KyMlgsllgPJ27wfWmP70l7fE86xvelPb4n7cX7e6KqKhobG5GdnQ1R7HqVSb+cQRFFEUOHDo31MLplsVji8g9IrPF9aY/vSXt8TzrG96U9viftxfN70t3MSQsukiUiIqK4w4BCREREcYcBJQr0ej0ef/xx6PX6WA8lrvB9aY/vSXt8TzrG96U9viftDaT3pF8ukiUiIqKBjTMoREREFHcYUIiIiCjuMKAQERFR3GFAISIiorjDgNIH/va3v2HKlClISEhAcnIybrjhhlgPKW7IsoxLLrkEgiDg4MGDsR5OzJw4cQL33HMPcnNzkZCQgLy8PDz++OPwer2xHlqfe+WVVzBixAgYDAZMmTIF+/fvj/WQYmbt2rW47LLLYDabkZ6ejhtuuAFFRUWxHlZceeqppyAIAh5++OFYDyXmzpw5g9tvvx0pKSlISEjAuHHj8Pnnn8d6WD3GgBJlf/nLX3DHHXfgrrvuwldffYVPP/0UixYtivWw4sZPfvITZGdnx3oYMffdd99BURT85je/wZEjR/D888/jtddew2OPPRbrofWpt99+GytXrsTjjz+OL774AuPHj8f8+fNRVVUV66HFxM6dO7Fs2TLs3bsXhYWF8Pl8mDdvHlwuV6yHFhc+++wz/OY3v8HFF18c66HEXH19PS6//HLodDp8+OGH+Oabb/Dss88iOTk51kPrOZWixufzqUOGDFF/+9vfxnoocenvf/+7esEFF6hHjhxRAahffvllrIcUV55++mk1Nzc31sPoU5MnT1aXLVvW+nUgEFCzs7PVtWvXxnBU8aOqqkoFoO7cuTPWQ4m5xsZGddSoUWphYaE6Y8YM9aGHHor1kGLq0UcfVa+44opYDyOiOIMSRV988QXOnDkDURQxYcIEZGVlYcGCBTh8+HCshxZzlZWVWLJkCf7whz/AaDTGejhxyW63w2azxXoYfcbr9eLAgQOYM2dO6zVRFDFnzhzs2bMnhiOLH3a7HQAG1Z+LzixbtgzXXXdd0J+Xwez//u//cOmll+Lmm29Geno6JkyYgDfeeCPWw+oVBpQoOnbsGADgF7/4BX7605/igw8+QHJyMmbOnIm6uroYjy52VFXFnXfeiR//+Me49NJLYz2cuFRSUoKXXnoJ9913X6yH0mdqamoQCASQkZERdD0jIwMVFRUxGlX8UBQFDz/8MC6//HJcdNFFsR5OTL311lv44osvsHbt2lgPJW4cO3YM69evx6hRo/DRRx9h6dKlePDBB/Hmm2/Gemg9xoDSA//5n/8JQRC6/NWypgAA/uu//gsLFy7EpEmTsGHDBgiCgHfeeSfGv4vIC/V9eemll9DY2Ig1a9bEeshRF+p7cr4zZ87gmmuuwc0334wlS5bEaOQUb5YtW4bDhw/jrbfeivVQYqqsrAwPPfQQ/vSnP8FgMMR6OHFDURRMnDgRTz75JCZMmIB7770XS5YswWuvvRbrofWYNtYD6I9WrVqFO++8s8vnjBw5EmfPngUAXHjhha3X9Xo9Ro4ciVOnTkVziDER6vuyfft27Nmzp91ZEZdeeiluu+22fp342wr1PWlRXl6OWbNmYfr06Xj99dejPLr4kpqaCo1Gg8rKyqDrlZWVyMzMjNGo4sPy5cvxwQcfYNeuXRg6dGishxNTBw4cQFVVFSZOnNh6LRAIYNeuXXj55ZchyzI0Gk0MRxgbWVlZQZ81ADBmzBj85S9/idGIeo8BpQfS0tKQlpbW7fMmTZoEvV6PoqIiXHHFFQAAn8+HEydOYPjw4dEeZp8L9X158cUX8atf/ar16/LycsyfPx9vv/02pkyZEs0h9rlQ3xOgeeZk1qxZrTNtoji4JjglScKkSZOwbdu21q34iqJg27ZtWL58eWwHFyOqquKBBx7A5s2bsWPHDuTm5sZ6SDE3e/ZsHDp0KOjaXXfdhQsuuACPPvrooAwnAHD55Ze324JeXFzcrz9rGFCiyGKx4Mc//jEef/xx5OTkYPjw4Vi3bh0A4Oabb47x6GJn2LBhQV+bTCYAQF5e3qD9r8MzZ85g5syZGD58OJ555hlUV1e3PjaYZg9WrlyJxYsX49JLL8XkyZPxwgsvwOVy4a677or10GJi2bJl2LRpE9577z2YzebWtThWqxUJCQkxHl1smM3mdmtwEhMTkZKSMqjX5qxYsQLTp0/Hk08+iR/+8IfYv38/Xn/99X49E8uAEmXr1q2DVqvFHXfcgaamJkyZMgXbt2/v33vTKeIKCwtRUlKCkpKSdiFNHUQHjv/7v/87qqur8fOf/xwVFRW45JJL8I9//KPdwtnBYv369QCAmTNnBl3fsGFDt7cOaXC57LLLsHnzZqxZswa//OUvkZubixdeeAG33XZbrIfWY4I6mP71IyIion5hcN3kJiIion6BAYWIiIjiDgMKERERxR0GFCIiIoo7DChEREQUdxhQiIiIKO4woBAREVHcYUAhIiKiuMOAQkRERHGHAYWIiIjiDgMKERERxR0GFCIiIoo7/z+Fw8r0XdhCOwAAAABJRU5ErkJggg==\n"
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "%%writefile app.py\n",
        "st.title(\"توقع درجاتك مع الذكاء الاصطناعي الخاص بنا \")\n",
        "y_pred_test = monkey.predict(x_test)\n",
        "accuracy = monkey.score(x_test,y_test) * 100\n",
        "print(f\"دقة النموذج الحاليا {accuracy}\")\n",
        "user_saat = st.number_input(\" :كم ساعة ذاكرت \")\n",
        "user_drink = st.selectbox(\"وش شربت ؟[ قهوه = 0 عصير = 1 شاي = ]2 : \")\n",
        "user_input = [[user_saat,user_drink]]\n",
        "input_pca = pca.transform(user_input)\n",
        "opo = monkey.predict(input_pca)\n",
        "print(opo)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "dqHGv6B1sPiO",
        "outputId": "36911d9b-8adb-414c-cc02-33b5593581b0"
      },
      "execution_count": 25,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Overwriting app.py\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "! npm install -g localtunnel\n",
        "! streamlit run app.py &>/dev/null &\n",
        "! npx localtunnel --port 8501"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "LJE14B7Bzxof",
        "outputId": "d4e7c020-d6b0-423d-c37f-84b808605529"
      },
      "execution_count": 29,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\u001b[1G\u001b[0K⠙\u001b[1G\u001b[0K⠹\u001b[1G\u001b[0K⠸\u001b[1G\u001b[0K⠼\u001b[1G\u001b[0K⠴\u001b[1G\u001b[0K⠦\u001b[1G\u001b[0K⠧\u001b[1G\u001b[0K⠇\u001b[1G\u001b[0K⠏\u001b[1G\u001b[0K⠋\u001b[1G\u001b[0K⠙\u001b[1G\u001b[0K⠹\u001b[1G\u001b[0K⠸\u001b[1G\u001b[0K⠼\u001b[1G\u001b[0K\n",
            "changed 22 packages in 2s\n",
            "\u001b[1G\u001b[0K⠼\u001b[1G\u001b[0K\n",
            "\u001b[1G\u001b[0K⠼\u001b[1G\u001b[0K3 packages are looking for funding\n",
            "\u001b[1G\u001b[0K⠼\u001b[1G\u001b[0K  run `npm fund` for details\n",
            "\u001b[1G\u001b[0K⠼\u001b[1G\u001b[0K\u001b[1G\u001b[0K⠙\u001b[1G\u001b[0K⠹\u001b[1G\u001b[0K⠸\u001b[1G\u001b[0K⠼\u001b[1G\u001b[0K⠴\u001b[1G\u001b[0K⠦\u001b[1G\u001b[0Kyour url is: https://thin-maps-share.loca.lt\n",
            "^C\n"
          ]
        }
      ]
    }
  ]
}